// Seeded public topographic map sources.
// Each source is a known free government-provided topographic map resource.
// Coverage is approximate and should be refined over time.

export const seedSources = [
  {
    id: 'usgs-topoview',
    countryCode: 'US',
    region: 'United States',
    agency: 'U.S. Geological Survey',
    sourceType: 'api',
    baseUrl: 'https://ngmdb.usgs.gov/topoview/viewer/',
    coverage: { minLat: 18, maxLat: 72, minLon: -180, maxLon: -66 },
    minScale: 24000,
    maxScale: 250000,
    formats: ['geopdf', 'geotiff'],
    license: 'Public Domain',
    accessNotes: 'Use topoView API or National Map Downloader to find map sheets.',
    isDirectDownload: false,
  },
  {
    id: 'nrcan-toporama',
    countryCode: 'CA',
    region: 'Canada',
    agency: 'Natural Resources Canada',
    sourceType: 'dashboard',
    baseUrl: 'https://atlas.gc.ca/toporama/en/index.html',
    coverage: { minLat: 42, maxLat: 84, minLon: -141, maxLon: -52 },
    minScale: 50000,
    maxScale: 250000,
    formats: ['geopdf', 'geotiff'],
    license: 'Open Government Licence - Canada',
    accessNotes: 'CanMatrix and CanTopo via GeoGratis; map sheet numbers use NTS.',
    isDirectDownload: false,
  },
  {
    id: 'ordnance-survey-opendata',
    countryCode: 'GB',
    region: 'United Kingdom',
    agency: 'Ordnance Survey',
    sourceType: 'api',
    baseUrl: 'https://osdatahub.os.uk/downloads/open',
    coverage: { minLat: 49.9, maxLat: 60.9, minLon: -8.7, maxLon: 1.8 },
    minScale: 10000,
    maxScale: 50000,
    formats: ['geopackage', 'gml', 'shapefile'],
    license: 'Open Government Licence',
    accessNotes: 'OS OpenMap Local, OS Terrain 50, OS VectorMap District via OS Data Hub API.',
    isDirectDownload: false,
  },
  {
    id: 'geoscience-australia',
    countryCode: 'AU',
    region: 'Australia',
    agency: 'Geoscience Australia',
    sourceType: 'dashboard',
    baseUrl: 'https://www.ga.gov.au/scientific-topics/national-location-information/topographic-maps-data/topographic-maps',
    coverage: { minLat: -44, maxLat: -10, minLon: 113, maxLon: 154 },
    minScale: 50000,
    maxScale: 250000,
    formats: ['pdf', 'geotiff'],
    license: 'Creative Commons BY 4.0',
    accessNotes: 'AUSTopo and historical topographic series via map index dashboards.',
    isDirectDownload: false,
  },
  {
    id: 'linz-nz',
    countryCode: 'NZ',
    region: 'New Zealand',
    agency: 'Land Information New Zealand',
    sourceType: 'api',
    baseUrl: 'https://data.linz.govt.nz/',
    coverage: { minLat: -48, maxLat: -34, minLon: 166, maxLon: 179 },
    minScale: 25000,
    maxScale: 250000,
    formats: ['geopdf', 'geotiff'],
    license: 'Creative Commons BY 4.0',
    accessNotes: 'NZ Topo50 and Topo250 via LINZ Data Service.',
    isDirectDownload: false,
  },
];
